import type {
  Appearance,
  ItemDefinition,
  EquipmentSlot,
  MobDefinition,
  QuestDefinition,
  SkillDefinition,
} from './types.js';

export const STATE_SCHEMA_VERSION = 3 as const;
export const EQUIPMENT_SLOTS: EquipmentSlot[] = [
  'weapon',
  'armor',
  'helmet',
  'gloves',
  'legs',
  'feet',
  'offhand',
  'ring1',
  'ring2',
  'earring1',
  'earring2',
  'belt',
  'cloak',
  'amulet',
];
export const WORLD = {
  title: 'ИРИЙ',
  zone: 'Берёзовый Брод',
  description:
    'За частоколом шумит старый лес. У брода сходятся тропы ратников, травниц и тех, кого лучше не встречать после заката.',
} as const;
export const DEFAULT_APPEARANCE: Appearance = {
  gender: 'male',
  hair: 'dark',
  hairStyle: 'short',
  skin: 'light',
  mark: 'none',
};
export const SKILLS: SkillDefinition[] = [
  {
    id: 'heavyStrike',
    name: 'Тяжёлый удар',
    description:
      'Мощный удар оружием: 160% обычного урона. Применяется автоматически, когда готов.',
    manaCost: 6,
    cooldownTurns: 3,
    policy: 'onCooldown',
  },
  {
    id: 'ward',
    name: 'Заслон',
    description:
      'Умение снаряжения уменьшает урон следующей вражеской атаки на 50%. Не мешает обычному удару.',
    manaCost: 5,
    cooldownTurns: 4,
    policy: 'onCooldown',
  },
  {
    id: 'mend',
    name: 'Живая вода',
    description: 'Восстанавливает здоровье вместо удара, если осталось не более 35% здоровья.',
    manaCost: 10,
    cooldownTurns: 4,
    policy: 'healthBelow',
    healthBelow: 0.35,
  },
  {
    id: 'flurry',
    name: 'Двойной порез',
    description:
      'Два быстрых удара кинжалом, каждый наносит 75% обычного урона и отдельно проверяет попадание и критический удар.',
    manaCost: 5,
    cooldownTurns: 2,
    policy: 'onCooldown',
  },
  {
    id: 'secondWind',
    name: 'Перевести дух',
    description: 'Восстанавливает 25% здоровья вместо удара, когда осталось не более 35% здоровья.',
    manaCost: 7,
    cooldownTurns: 5,
    policy: 'healthBelow',
    healthBelow: 0.35,
  },
];
export const SKILL_BY_ID = Object.fromEntries(SKILLS.map((skill) => [skill.id, skill])) as Record<
  SkillDefinition['id'],
  SkillDefinition
>;

// Stable IDs are storage keys from schema v1, not names in the world. Keep them when changing copy.
export const ITEMS: ItemDefinition[] = [
  {
    id: 'hunting-coat',
    grantedSkills: ['secondWind'],
    name: 'Охотничья стеганка',
    slot: 'armor',
    rarity: 'uncommon',
    requiredLevel: 2,
    stats: { armor: 65, maxHp: 10, attack: 2 },
    description: 'Зелёная стеганка с коротким меховым воротником. В ней удобно идти по следу.',
    visual: { armorStyle: 'cloth', armorVariant: 'hunter', accentColor: '#71835b' },
  },
  {
    id: 'watch-mail',
    grantedSkills: ['ward'],
    name: 'Кольчуга речного дозора',
    slot: 'armor',
    rarity: 'rare',
    requiredLevel: 3,
    stats: { armor: 155, maxMana: 10 },
    description: 'Железные кольца под синей накидкой речных дозорных. Найдена у лесной стоянки.',
    visual: { armorStyle: 'chain', armorVariant: 'watch', accentColor: '#597989' },
  },
  {
    id: 'oath-lamellar',
    grantedSkills: ['ward', 'secondWind'],
    name: 'Пластинчатый доспех дружинника',
    slot: 'armor',
    rarity: 'epic',
    requiredLevel: 4,
    stats: { armor: 195, maxHp: 18, attack: 1 },
    description:
      'Ряды железных пластин связаны сыромятными ремнями; красный пояс отмечает дружинную службу.',
    visual: { armorStyle: 'chain', armorVariant: 'oath', accentColor: '#ad6653' },
  },
  {
    id: 'training-hammer',
    grantedSkills: ['heavyStrike'],
    handType: 'oneHand',
    name: 'Дубовая булава',
    slot: 'weapon',
    rarity: 'common',
    requiredLevel: 1,
    stats: { attack: 2 },
    description: 'Простая булава, которую выдал кузнец перед первым дозором.',
    visual: { weaponStyle: 'mace', accentColor: '#897044' },
  },
  {
    id: 'recruit-vest',
    grantedSkills: ['secondWind'],
    name: 'Стёганая рубаха',
    slot: 'armor',
    rarity: 'common',
    requiredLevel: 1,
    stats: { armor: 35, maxHp: 4 },
    description: 'Льняная рубаха с плотной стёжкой бережёт от зубов и колючек.',
    visual: { armorStyle: 'cloth', accentColor: '#a88b56' },
  },
  {
    id: 'wolf-fang',
    grantedSkills: ['mend'],
    offhandType: 'talisman',
    name: 'Волчий оберег',
    slot: 'offhand',
    rarity: 'uncommon',
    requiredLevel: 1,
    stats: { attack: 1, maxHp: 3 },
    description: 'Белый клык на кожаном шнурке. Охотники верят, что он отводит беду.',
    visual: { accessoryStyle: 'talisman', accentColor: '#789163' },
  },
  {
    id: 'militia-hammer',
    grantedSkills: ['heavyStrike'],
    handType: 'twoHand',
    name: 'Топор лесного дозора',
    slot: 'weapon',
    rarity: 'uncommon',
    requiredLevel: 2,
    stats: { attack: 5 },
    description: 'Добротный топор кузнеца Твердислава, выкованный для стражей брода.',
    visual: { weaponStyle: 'axe', accentColor: '#74815c' },
  },
  {
    id: "miner's-boots",
    grantedSkills: ['ward'],
    name: 'Кольчуга болотного сторожа',
    slot: 'armor',
    rarity: 'uncommon',
    requiredLevel: 2,
    stats: { armor: 90, maxHp: 8 },
    description: 'Кольца потемнели от воды, но железо ещё держит удар.',
    visual: { armorStyle: 'chain', accentColor: '#738478' },
  },
  {
    id: 'abbey-tabard',
    grantedSkills: ['secondWind'],
    name: 'Доспех Берёзового Брода',
    slot: 'armor',
    rarity: 'rare',
    requiredLevel: 3,
    stats: { armor: 140, maxHp: 15 },
    description: 'Крепкий кожаный доспех с родовым узором старосты.',
    visual: { armorStyle: 'leather', accentColor: '#657f99' },
  },
  {
    id: 'defias-blade',
    grantedSkills: ['heavyStrike'],
    handType: 'oneHand',
    name: 'Меч лихого атамана',
    slot: 'weapon',
    rarity: 'rare',
    requiredLevel: 3,
    stats: { attack: 8, critChance: 0.02 },
    description: 'Широкий меч с насечками: каждая напоминает о чьей-то разбитой повозке.',
    visual: { weaponStyle: 'sword', accentColor: '#748cac' },
  },
  {
    id: 'northshire-signet',
    grantedSkills: ['mend', 'ward'],
    offhandType: 'talisman',
    name: 'Печать хранителя брода',
    slot: 'offhand',
    rarity: 'rare',
    requiredLevel: 3,
    stats: { maxHp: 10, maxMana: 15, attack: 2 },
    description: 'Береста под серебряной оправой хранит знак защитника поселения.',
    visual: { accessoryStyle: 'talisman', accentColor: '#8092a8' },
  },
  {
    id: 'thunder-axe',
    grantedSkills: ['heavyStrike'],
    handType: 'twoHand',
    name: 'Громовой секач',
    slot: 'weapon',
    rarity: 'epic',
    requiredLevel: 3,
    stats: { attack: 12, critChance: 0.04 },
    description: 'Древний топор с грозовым узором. Редкая добыча с болотных лиходеев.',
    visual: { weaponStyle: 'axe', accentColor: '#af88c4' },
  },

  {
    id: 'linen-hood',
    name: 'Стёганый подшлемник',
    slot: 'helmet',
    rarity: 'common',
    requiredLevel: 1,
    stats: { armor: 12 },
    grantedSkills: ['ward'],
    description: 'Льняной подшлемник с плотной простёжкой закрывает виски и затылок.',
    visual: { accessoryStyle: 'cloth', accentColor: '#a78a59' },
  },
  {
    id: 'watch-helmet',
    name: 'Шлем речного дозора',
    slot: 'helmet',
    rarity: 'rare',
    requiredLevel: 3,
    stats: { armor: 35, maxHp: 5 },
    grantedSkills: ['ward'],
    description: 'Железный шлем с наносником. На затылке выбито клеймо кузницы у брода.',
    visual: { accessoryStyle: 'iron', accentColor: '#688793' },
  },
  {
    id: 'linen-wraps',
    name: 'Льняные рукавицы',
    slot: 'gloves',
    rarity: 'common',
    requiredLevel: 1,
    stats: { armor: 8, maxHp: 2 },
    grantedSkills: [],
    description: 'Плотные рукавицы предохраняют ладони от заноз на древке.',
    visual: { accessoryStyle: 'cloth', accentColor: '#a78a59' },
  },
  {
    id: 'watch-gauntlets',
    name: 'Рукавицы речного дозора',
    slot: 'gloves',
    rarity: 'rare',
    requiredLevel: 3,
    stats: { armor: 25, attack: 1 },
    grantedSkills: [],
    description: 'Небольшие железные пластины нашиты на кожаные рукавицы.',
    visual: { accessoryStyle: 'iron', accentColor: '#688793' },
  },
  {
    id: 'linen-trousers',
    name: 'Холщовые порты',
    slot: 'legs',
    rarity: 'common',
    requiredLevel: 1,
    stats: { armor: 10, maxHp: 3 },
    grantedSkills: [],
    description: 'Плотные порты с обмотками. Колени дважды залатаны крепкой нитью.',
    visual: { accessoryStyle: 'cloth', accentColor: '#a78a59' },
  },
  {
    id: 'watch-greaves',
    name: 'Поножи речного дозора',
    slot: 'legs',
    rarity: 'rare',
    requiredLevel: 3,
    stats: { armor: 40, maxHp: 6 },
    grantedSkills: [],
    description: 'Железные накладки стянуты ремнями поверх синих портов.',
    visual: { accessoryStyle: 'iron', accentColor: '#688793' },
  },
  {
    id: 'birch-shield',
    name: 'Берёзовый щит',
    slot: 'offhand',
    offhandType: 'shield',
    rarity: 'uncommon',
    requiredLevel: 1,
    stats: { armor: 40, maxHp: 4 },
    grantedSkills: ['ward'],
    description: 'Круглый щит из склеенных дощечек. Кожаная кромка стянута железными скобами.',
    visual: { accessoryStyle: 'shield', accentColor: '#8c7950' },
  },
  {
    id: 'ford-shield',
    name: 'Щит хранителя брода',
    slot: 'offhand',
    offhandType: 'shield',
    rarity: 'rare',
    requiredLevel: 3,
    stats: { armor: 75, maxHp: 8 },
    grantedSkills: ['ward'],
    description: 'Речной узор нанесён синей краской вокруг железного умбона.',
    visual: { accessoryStyle: 'shield', accentColor: '#688793' },
  },
  {
    id: 'reed-dagger',
    name: 'Камышовый нож',
    slot: 'weapon',
    handType: 'oneHand',
    rarity: 'uncommon',
    requiredLevel: 2,
    stats: { attack: 4, critChance: 0.02 },
    grantedSkills: ['flurry'],
    description: 'Узкий нож болотных проводников. На рукояти следы смолы и крепкая обмотка.',
    visual: { weaponStyle: 'dagger', accessoryStyle: 'dagger', accentColor: '#71835b' },
  },
  {
    id: 'reed-parrying-dagger',
    name: 'Короткий камышовый нож',
    slot: 'offhand',
    offhandType: 'dagger',
    rarity: 'uncommon',
    requiredLevel: 2,
    stats: { attack: 2, critChance: 0.02 },
    grantedSkills: ['flurry'],
    description: 'Нож для второй руки. Его носят в паре с основным кинжалом.',
    visual: { accessoryStyle: 'dagger', accentColor: '#71835b' },
  },
  {
    id: 'sun-watch-armor',
    name: 'Доспех Солнцеворота',
    slot: 'armor',
    rarity: 'legendary',
    requiredLevel: 4,
    stats: { armor: 225, maxHp: 24, maxMana: 10 },
    grantedSkills: ['ward', 'secondWind'],
    description:
      'Червлёные пластины с медными краями. Кузнец соединил их в рисунок восходящего солнца.',
    visual: { armorStyle: 'chain', armorVariant: 'sun', accentColor: '#d89736' },
  },
  {
    id: 'sun-watch-helmet',
    name: 'Шлем Солнцеворота',
    slot: 'helmet',
    rarity: 'legendary',
    requiredLevel: 4,
    stats: { armor: 55, maxHp: 8 },
    grantedSkills: ['ward'],
    description: 'Низкий медный гребень повторяет лучи на нагруднике. Лицо остаётся открытым.',
    visual: { accessoryStyle: 'sun', accentColor: '#d89736' },
  },
  {
    id: 'sun-watch-gloves',
    name: 'Рукавицы Солнцеворота',
    slot: 'gloves',
    rarity: 'legendary',
    requiredLevel: 4,
    stats: { armor: 35, attack: 2 },
    grantedSkills: [],
    description: 'Червлёные пластины прикрывают кисти; медные заклёпки стоят вдоль каждого пальца.',
    visual: { accessoryStyle: 'sun', accentColor: '#d89736' },
  },
  {
    id: 'sun-watch-legs',
    name: 'Поножи Солнцеворота',
    slot: 'legs',
    rarity: 'legendary',
    requiredLevel: 4,
    stats: { armor: 60, maxHp: 10 },
    grantedSkills: [],
    description: 'Поверх тёмных портов уложены красные железные чешуи с тонкой медной каймой.',
    visual: { accessoryStyle: 'sun', accentColor: '#d89736' },
  },

  {
    id: 'linen-shoes',
    name: 'Плетёные лапти',
    slot: 'feet',
    rarity: 'common',
    requiredLevel: 1,
    stats: { armor: 8, maxHp: 2 },
    grantedSkills: [],
    description: 'Свежие лыковые лапти поверх плотных обмоток.',
    visual: { accessoryStyle: 'cloth', accentColor: '#a78a59' },
  },
  {
    id: 'watch-boots',
    name: 'Сапоги речного дозора',
    slot: 'feet',
    rarity: 'rare',
    requiredLevel: 3,
    stats: { armor: 25, maxHp: 5 },
    grantedSkills: [],
    description: 'Кожаные сапоги с железными накладками и высокими голенищами.',
    visual: { accessoryStyle: 'iron', accentColor: '#688793' },
  },
  {
    id: 'sun-watch-boots',
    name: 'Сапоги Солнцеворота',
    slot: 'feet',
    rarity: 'legendary',
    requiredLevel: 4,
    stats: { armor: 40, maxHp: 7 },
    grantedSkills: [],
    description:
      'Красные железные чешуи закрывают подъём стопы; медная кайма повторяет узор поножей.',
    visual: { accessoryStyle: 'sun', accentColor: '#d89736' },
  },
  {
    id: 'copper-ring',
    name: 'Медное кольцо',
    slot: 'ring1',
    equipSlots: ['ring1', 'ring2'],
    rarity: 'common',
    requiredLevel: 1,
    stats: { maxHp: 2 },
    grantedSkills: [],
    description: 'Простое кольцо из свёрнутой медной полоски.',
    visual: { accentColor: '#aa815b' },
  },
  {
    id: 'river-ring',
    name: 'Кольцо речного мастера',
    slot: 'ring1',
    equipSlots: ['ring1', 'ring2'],
    rarity: 'rare',
    requiredLevel: 3,
    stats: { attack: 1, maxMana: 5 },
    grantedSkills: [],
    description: 'Серебряный ободок с волнистой насечкой и тёмным речным камнем.',
    visual: { accentColor: '#688793' },
  },
  {
    id: 'copper-earring',
    name: 'Медная серьга',
    slot: 'earring1',
    equipSlots: ['earring1', 'earring2'],
    rarity: 'common',
    requiredLevel: 1,
    stats: { maxMana: 3 },
    grantedSkills: [],
    description: 'Небольшое медное кольцо с каплей янтаря.',
    visual: { accentColor: '#aa815b' },
  },
  {
    id: 'river-earring',
    name: 'Серьга речного мастера',
    slot: 'earring1',
    equipSlots: ['earring1', 'earring2'],
    rarity: 'rare',
    requiredLevel: 3,
    stats: { maxHp: 3, critChance: 0.005 },
    grantedSkills: [],
    description: 'Тонкая серебряная серьга с подвеской в форме лодки.',
    visual: { accentColor: '#688793' },
  },
  {
    id: 'woven-belt',
    name: 'Тканый пояс',
    slot: 'belt',
    rarity: 'uncommon',
    requiredLevel: 2,
    stats: { armor: 12, maxHp: 4 },
    grantedSkills: [],
    description: 'Широкий шерстяной пояс с красными ромбами на тёмной полосе.',
    visual: { accentColor: '#a65b4b' },
  },
  {
    id: 'traveller-cloak',
    name: 'Дорожный плащ',
    slot: 'cloak',
    rarity: 'uncommon',
    requiredLevel: 2,
    stats: { armor: 15, maxMana: 4 },
    grantedSkills: [],
    description: 'Суконный плащ застёгнут костяной пуговицей. По низу прошита узкая тесьма.',
    visual: { accentColor: '#71835b' },
  },
  {
    id: 'birch-amulet',
    name: 'Берестяная привеска',
    slot: 'amulet',
    rarity: 'uncommon',
    requiredLevel: 2,
    stats: { maxHp: 5, maxMana: 5 },
    grantedSkills: [],
    description: 'Сложенная береста в маленькой серебряной оправе. Её носят под воротом.',
    visual: { accentColor: '#a78a59' },
  },
];
export const MOBS: MobDefinition[] = [
  {
    id: 'wolf',
    name: 'Лесной волк',
    level: 1,
    hp: 22,
    attack: 4,
    armor: 0,
    xp: 12,
    copper: 4,
    location: 'Берёзовая опушка',
    description:
      'Волки обходят пастушьи костры и тянутся к стадам у брода. У тропы остались потерянные вещи пастухов.',
    loot: [
      { itemId: 'wolf-fang', chance: 0.08 },
      { itemId: 'recruit-vest', chance: 0.1 },
      { itemId: 'hunting-coat', chance: 0.015 },
      { itemId: 'linen-hood', chance: 0.035 },
      { itemId: 'linen-wraps', chance: 0.04 },
      { itemId: 'linen-trousers', chance: 0.04 },
      { itemId: 'birch-shield', chance: 0.02 },
      { itemId: 'linen-shoes', chance: 0.04 },
      { itemId: 'copper-ring', chance: 0.025 },
      { itemId: 'copper-earring', chance: 0.025 },
    ],
  },
  {
    id: 'kobold',
    name: 'Трухлявый страж',
    level: 2,
    hp: 38,
    attack: 7,
    armor: 60,
    xp: 21,
    copper: 7,
    location: 'Старый бор',
    description:
      'Лесные стражи вышли к лесорубной тропе, когда кто-то выжег охранные знаки на берёзах.',
    loot: [
      { itemId: "miner's-boots", chance: 0.07 },
      { itemId: 'militia-hammer', chance: 0.04 },
      { itemId: 'watch-mail', chance: 0.02 },
      { itemId: 'reed-dagger', chance: 0.035 },
      { itemId: 'reed-parrying-dagger', chance: 0.025 },
      { itemId: 'watch-helmet', chance: 0.015 },
      { itemId: 'woven-belt', chance: 0.025 },
      { itemId: 'traveller-cloak', chance: 0.025 },
      { itemId: 'birch-amulet', chance: 0.02 },
    ],
  },
  {
    id: 'defias',
    name: 'Болотный лиходей',
    level: 3,
    hp: 65,
    attack: 10,
    armor: 100,
    xp: 35,
    copper: 12,
    location: 'Камышовые топи',
    description: 'Люди болотного атамана требуют незаконную пошлину с каждого, кто идёт к броду.',
    loot: [
      { itemId: 'defias-blade', chance: 0.04 },
      { itemId: 'northshire-signet', chance: 0.02 },
      { itemId: 'thunder-axe', chance: 0.005 },
      { itemId: 'oath-lamellar', chance: 0.006 },
      { itemId: 'watch-gauntlets', chance: 0.025 },
      { itemId: 'watch-greaves', chance: 0.025 },
      { itemId: 'ford-shield', chance: 0.02 },
      { itemId: 'sun-watch-armor', chance: 0.001 },
      { itemId: 'sun-watch-helmet', chance: 0.002 },
      { itemId: 'sun-watch-gloves', chance: 0.002 },
      { itemId: 'sun-watch-legs', chance: 0.002 },
      { itemId: 'sun-watch-boots', chance: 0.002 },
      { itemId: 'watch-boots', chance: 0.025 },
      { itemId: 'river-ring', chance: 0.02 },
      { itemId: 'river-earring', chance: 0.02 },
    ],
  },
];
export const QUESTS: QuestDefinition[] = [
  {
    id: 'wolves-at-the-gate',
    title: 'Волчья тропа',
    giver: 'Дарёна-травница',
    requiredLevel: 1,
    description:
      'У Дарёны пропали две овцы, а пастух нашёл следы стаи у берёзовой опушки. Отгони волков от тропы, пока оставшиеся овцы не стали добычей.',
    objective: { mobId: 'wolf', count: 8 },
    rewards: { xp: 55, copper: 35, itemId: 'militia-hammer' },
  },
  {
    id: 'kobold-cleanup',
    title: 'Зарубки на берёзах',
    giver: 'Староста Богдан',
    requiredLevel: 2,
    prerequisite: 'wolves-at-the-gate',
    description:
      'Кто-то выжег охранные зарубки на берёзах. Стражи старого бора вышли к лесорубной тропе и не пропускают обозы с зерном. Оттесни их, пока мы восстановим знаки.',
    objective: { mobId: 'kobold', count: 10 },
    rewards: { xp: 100, copper: 70, itemId: 'abbey-tabard' },
  },
  {
    id: 'defias-brotherhood',
    title: 'Пошлина с брода',
    giver: 'Яромир-дозорный',
    requiredLevel: 3,
    prerequisite: 'kobold-cleanup',
    description:
      'Болотный атаман обложил переправу незаконной данью. Прогони его людей из камышей, чтобы купцы могли пройти к Берёзовому Броду.',
    objective: { mobId: 'defias', count: 12 },
    rewards: { xp: 175, copper: 120, itemId: 'northshire-signet' },
  },
];
export const MOB_BY_ID = Object.fromEntries(MOBS.map((mob) => [mob.id, mob])) as Record<
  MobDefinition['id'],
  MobDefinition
>;
export const ITEM_BY_ID = Object.fromEntries(ITEMS.map((item) => [item.id, item])) as Record<
  ItemDefinition['id'],
  ItemDefinition
>;
export const QUEST_BY_ID = Object.fromEntries(QUESTS.map((quest) => [quest.id, quest])) as Record<
  QuestDefinition['id'],
  QuestDefinition
>;
export const COMBAT_RULES = {
  armorBase: 400,
  armorPerLevel: 85,
  criticalMultiplier: 2,
  baseCritChance: 0.05,
  baseHitChance: 0.95,
  hitPenaltyPerLevel: 0.02,
  heavyStrikeMultiplier: 1.6,
  flurryHitMultiplier: 0.75,
  secondWindFraction: 0.25,
  wardReduction: 0.5,
} as const;
export const TICK_MS = 3_000;
export const MAX_OFFLINE_MS = 8 * 60 * 60 * 1_000;
export const MAX_INVENTORY = 100;
export const MAX_LEVEL = 20;
export const MAX_LOG_ENTRIES = 40;
export const MAX_RECENT_EVENTS = 30;
